## Q1 You are given a space separated list of numbers.Your task is to print a reversed NumPy array with the element type float. 
link-https://www.hackerrank.com/challenges/np-arrays/problem

In [1]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr=numpy.array(arr[::-1],float)
    return arr
        
        

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

 1 2 3 4 5 6 7 8 9


[9. 8. 7. 6. 5. 4. 3. 2. 1.]


## Q2.You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.
link-https://www.hackerrank.com/challenges/np-shape-reshape/problem?isFullScreen=true

In [2]:
import numpy
arr = input().strip().split(' ')
arr=numpy.reshape(arr,(3,3))
print(numpy.array(arr,int))

 1 2 3 4 5 6 7 8 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Q3 You are given a X integer array matrix with space separated elements ( = rows and  = columns).Your task is to print the transpose and flatten results.
link-https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem?isFullScreen=true

In [3]:
import numpy
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())




 2 2 
 1 3
 3 4


[[1 3]
 [3 4]]
[1 3 3 4]


## Q4 You are given two integer arrays of size X and X ( &  are rows, and  is the column). Your task is to concatenate the arrays along axis .
link-https://www.hackerrank.com/challenges/np-concatenate/problem?isFullScreen=true

In [7]:
import numpy
n,m,p=map(int,input().split())
arr1=numpy.array([input().strip().split() for _ in range(n)], int)
arr2=numpy.array([input().strip().split() for _ in range(m)], int)
print (numpy.concatenate((arr1, arr2), axis = 0))

 1 1 2
 1 3
 1 5


[[1 3]
 [1 5]]


## Q5 You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.
link-https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?isFullScreen=true

In [8]:
import numpy
arr = input().strip().split(' ')
arr=numpy.array(arr,int)
print(numpy.zeros(arr,numpy.int64))
print(numpy.ones(arr,numpy.int64))


 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Q6 Your task is to print an array of size X with its main diagonal elements as 's and 's everywhere else.
link=https://www.hackerrank.com/challenges/np-eye-and-identity/problem?isFullScreen=true

In [9]:
import numpy
numpy.set_printoptions(legacy='1.13')
n,m=map(int,input().split())
print(numpy.eye(n,m))

 3 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Q7 You are given two integer arrays,  and  of dimensions X.
Your task is to perform the following operations:

Add ( + )
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )
link-https://www.hackerrank.com/challenges/np-array-mathematics/problem

In [10]:
import numpy
n,m=map(int,input().split())
arr1=numpy.array([input().strip().split() for _ in range(n)],int)
arr2=numpy.array([input().strip().split() for _ in range(n)],int)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1//arr2)
print(arr1 % arr2)
print(arr1**arr2)

 1 4
 1 2 3 4
 5 6 7 8


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Q 8 You are given a 1-D array, . Your task is to print the floor ,ceil  and  of all the elements of .
link-https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem?isFullScreen=true

In [12]:
import numpy
numpy.set_printoptions(legacy='1.13')
arr=input().strip().split(' ')
arr=numpy.array(arr,float)
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint((arr)))

 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Q9 You are given a 2-D array with dimensions X.Your task is to perform the  tool over axis  and then find the  of that result.
link-https://www.hackerrank.com/challenges/np-sum-and-prod/problem?isFullScreen=true

In [13]:
import numpy
n,m=map(int,input().split())
arr=numpy.array([input().strip().split() for _ in range(n)],int)
arr=numpy.sum(arr, axis=0)
print(numpy.prod(arr, axis=0))




 2 2
 1 2
 3 4


24


## Q10 You are given a 2-D array with dimensions X.Your task is to perform the min function over axis  and then find the max of that.
link-https://www.hackerrank.com/challenges/np-min-and-max/problem?isFullScreen=true

In [14]:
import numpy
n,m=map(int,input().split())
arr=numpy.array([input().strip().split() for _ in range(n)],int)
arr=numpy.min(arr, axis=1)
print(numpy.max(arr, axis=0))

 4 2
 2 5
 3 7
 1 3
 4 0


3


## Q11 You are given a 2-D array of size X.
Your task is to find:

The mean along axis 
The var along axis 
The std along axis
link=https://www.hackerrank.com/challenges/np-mean-var-and-std/problem?isFullScreen=true

In [15]:
import numpy
n,m=map(int,input().split())
arr=numpy.array([input().strip().split() for _ in range(n)],int)
print(numpy.mean(arr, axis=1))
print(numpy.var(arr, axis=0))
a=numpy.std(arr, axis=None)
print(round(a,11))


 2 2
 1 2
 3 4


[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## Q12 You are given two arrays  and . Both have dimensions of X.
Your task is to compute their matrix product.
link-https://www.hackerrank.com/challenges/np-dot-and-cross/problem?isFullScreen=true

In [16]:
import numpy
n=int(input())
a=numpy.array([input().strip().split() for _ in range(n)],int)
b=numpy.array([input().strip().split() for _ in range(n)],int)
print(numpy.dot(a,b))

 2
 1 2
 3 4
 1 2
 3 4


[[ 7 10]
 [15 22]]


## Q13 You are given two arrays:  and .
Your task is to compute their inner and outer product.
link-https://www.hackerrank.com/challenges/np-inner-and-outer/problem?isFullScreen=true

In [17]:
import numpy
a=numpy.array(input().strip().split(' '),int)
b=numpy.array(input().strip().split(' '),int)
print(numpy.inner(a,b))
print(numpy.outer(a,b))

 0 1
 2 3


3
[[0 0]
 [2 3]]


## Q14 You are given the coefficients of a polynomial .
Your task is to find the value of  at point .
link-https://www.hackerrank.com/challenges/np-polynomials/problem?isFullScreen=true

In [18]:
import numpy
arr=input().strip().split()
arr=numpy.array(arr,float)
x=float(input())
print(numpy.polyval(arr,x))

 1.1 2 3
 0


3.0


## Q15 You are given a square matrix  with dimensions X. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.
link-https://www.hackerrank.com/challenges/np-linear-algebra/problem

In [19]:
import numpy
n=int(input())
arr=numpy.array([input().strip().split() for _ in range(n)],float)
a=numpy.linalg.det(arr)
print(round(a,2))

 2
 1.1 1.1
 1.1 1.1


0.0
